[package]
name = "camera_models"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = { version = "0.5.1", default-features = false, features = ["std"] }
cv = "0.6.0"
nalgebra = { version = "0.32.3", features = ["rayon", "serde"] }
